# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WaveNet Vocoder with Collapsed Speech Suppression
description: '' # write a nice description for your blog
baseurl: '/LpcConstrainedWaveNet_demo' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site http://www.example.com
# google_analytics: 'UA-XXXXXX-X'
# twitter_username: 'twitter_username'

# Build settings
markdown: kramdown

permalink: '/:title/'

plugins: [jekyll-paginate]

paginate: 10
#© 2019 GitHub, Inc.